Repository PeaPodTechnologies/PeaPod, pull requests merged in 2021-06, with the labels that each got.

#11 [META] - Code Ownership
  .github/CODEOWNERS
Labels: Scope: Meta, Status: Review Needed, Type: New Feature

#18 Humidification Prototype
  deliverables/aeroponics/hardware/bom.csv
  deliverables/aeroponics/hardware/schematics/aeroponics_schematic.json
  deliverables/aeroponics/hardware/schematics/aeroponics_schematic.png
Labels: Scope: Deliverable, Status: In Progress, Type: New Feature

#19 Better Readme
  README.md
  assets/blackbox.png
  assets/features.png
Labels: Scope: Documentation, Scope: Meta, Status: In Progress, Type: New Feature

#23 Issue Template for Prototyping
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/prototype.md
  README.md
Labels: Scope: Meta, Status: Review Needed, Type: New Feature

#16 Design Proposal: First Draft
  docs/design/designproposal/DesignProposal.pdf
  docs/design/designproposal/DesignProposal.tex
  docs/design/designproposal/images/blackbox.png
  docs/design/designproposal/images/features.png
  docs/design/designproposal/references.bib
  docs/design/designproposal/report.cls
Labels: Scope: Documentation, Status: Review Needed, Type: New Feature

#29 Fixed PR Template
  .github/pull_request_template.md
Labels: Scope: Meta, Status: Review Needed, Type: Bug

#38 Aeroponics Prototype
  deliverables/aeroponics/aeroponics_bom_purchase.csv
Labels: Scope: Deliverable, Status: Review Needed, Type: New Feature

#37 Housing Prototype
  deliverables/housing/frame/ExtrusionCap.stl
  deliverables/housing/frame/brackets/LBracketA.stl
  deliverables/housing/frame/brackets/LBracketB.stl
  deliverables/housing/frame/brackets/TBracket.stl
  deliverables/housing/housing_bom_fabrication.csv
  deliverables/housing/housing_bom_purchase.csv
  deliverables/housing/trays/TrayMountA.stl
  deliverables/housing/trays/TrayMountB.stl
  deliverables/housing/trays/growtray/GrowPlateQuarter.stl
  deliverables/housing/trays/growtray/GrowPlateWasher.stl
  deliverables/housing/trays/growtray/NozzleMountA.stl
  deliverables/housing/trays/growtray/NozzleMountB.stl
  deliverables/housing/trays/growtray/SealStrip.stl
Labels: Scope: Deliverable, Status: Review Needed, Type: New Feature

#41 Added ToC to Readme
  README.md
Labels: Scope: Documentation, Status: Review Needed, Type: Improvement
