Repository PeaPodTechnologies/PeaPod, pull requests merged in 2021-07, with the labels that each got.

#51 CAD Holes Resized, Nozzle Mounting Updated
  deliverables/housing/frame/brackets/LBracketA.stl
  deliverables/housing/frame/brackets/LBracketB.stl
  deliverables/housing/frame/brackets/TBracket.stl
  deliverables/housing/housing_bom_purchase.csv
  deliverables/housing/trays/TrayMountA.stl
  deliverables/housing/trays/TrayMountB.stl
  deliverables/housing/trays/growtray/GrowPlateQuarter.stl
  deliverables/housing/trays/growtray/GrowPlateWasher.stl
  deliverables/housing/trays/growtray/NozzleMountA.stl
  deliverables/housing/trays/growtray/NozzleMountB.stl
Labels: Scope: Deliverable, Status: Review Needed, Type: Improvement

#69 Fixed Broken Images
  README.md
Labels: Scope: Documentation, Status: Review Needed, Type: Bug

#67 Fixed Extrusion Cap, Seal Strip Sizings
  deliverables/housing/frame/ExtrusionCap.stl
  deliverables/housing/trays/growtray/SealStrip.stl
Labels: Scope: Deliverable, Status: Review Needed, Type: Bug

#63 Design Report Section: Constraints
  docs/design/designreport/DesignReport.pdf
  docs/design/designreport/DesignReport.tex
Labels: Scope: Documentation, Status: Review Needed, Type: New Feature

#88 Solution Overview Revisions
  docs/design/solutionoverview/SolutionOverview.pdf
  docs/design/solutionoverview/SolutionOverview.tex
Labels: Priority: High, Scope: Documentation, Status: Review Needed, Type: Improvement

#80 Animation Storyboard
  docs/animation/storyboard/README.md
  docs/animation/storyboard/frames/frame-A1a.jpg
  docs/animation/storyboard/frames/frame-A1b.jpg
  docs/animation/storyboard/frames/frame-A1c.jpg
  docs/animation/storyboard/frames/frame-A2-1.jpg
  docs/animation/storyboard/frames/frame-A2-2.jpg
  docs/animation/storyboard/frames/frame-A3.jpg
  docs/animation/storyboard/frames/frame-B1a.jpg
  docs/animation/storyboard/frames/frame-B1b.jpg
  docs/animation/storyboard/frames/frame-B1c.jpg
  docs/animation/storyboard/frames/frame-B1d.jpg
  docs/animation/storyboard/frames/frame-B1e.jpg
  docs/animation/storyboard/frames/frame-B1f.jpg
  docs/animation/storyboard/frames/frame-B1g.jpg
  docs/animation/storyboard/frames/frame-B1h.jpg
  docs/animation/storyboard/frames/frame-B1i.jpg
  docs/animation/storyboard/frames/frame-B1j.jpg
  docs/animation/storyboard/frames/frame-B1k.jpg
  docs/animation/storyboard/frames/frame-B2a.jpg
  docs/animation/storyboard/frames/frame-B2b.jpg
  docs/animation/storyboard/frames/frame-B2c.jpg
  docs/animation/storyboard/frames/frame-B2d.jpg
  docs/animation/storyboard/frames/frame-B2e.jpg
  docs/animation/storyboard/frames/frame-C1.jpg
  docs/animation/storyboard/frames/frame-D1.jpg
  docs/animation/storyboard/frames/frame-D2.jpg
  docs/animation/storyboard/frames/frame-D3.jpg
  docs/animation/storyboard/frames/frame-D4.jpg
  docs/animation/storyboard/frames/frame-D5.jpg
  docs/animation/storyboard/frames/frame-E1.jpg
  docs/animation/storyboard/frames/frame-E2.jpg
Labels: Scope: Documentation, Status: In Progress, Type: New Feature

#87 Fixed #76
  docs/design/designreport/DesignReport.pdf
  docs/design/designreport/DesignReport.tex
Labels: Status: Review Needed

#75 Design Report: Performance Criteria
  docs/design/designreport/DesignReport.pdf
  docs/design/designreport/DesignReport.tex
Labels: Scope: Documentation, Status: In Progress, Type: New Feature

#96 Merging Innovation to Staging (Issue #59)
  docs/design/designreport/DesignReport.pdf
  docs/design/designreport/DesignReport.tex
Labels: Priority: High, Scope: Documentation, Status: Review Needed

#95 Merging Terrestrial Potential to Staging (Issue #62)
  docs/design/designreport/DesignReport.tex
Labels: Priority: High, Scope: Documentation, Status: Review Needed

#94 Design Report: Abstract and Description A+B
  docs/design/designreport/DesignReport.pdf
  docs/design/designreport/DesignReport.tex
Labels: Priority: High, Scope: Documentation, Status: Review Needed

#101 Link to Final Animation
  README.md
Labels: Scope: Documentation, Status: Review Needed, Type: New Feature
